/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;
import Clases.c_auxilio_vial;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
/**
 *
 * @author 1000a
 */
public class AuxilioVial extends javax.swing.JFrame {

    /**
     * Creates new form AuxilioVial
     */
    public AuxilioVial() {
        initComponents();
        this.setLocationRelativeTo(null); //para que el formulario se quede en el centro
        this.setResizable(false);
        
        folio.setEnabled(false); //para que no se pueda modificar el id
        
        c_auxilio_vial ca = new c_auxilio_vial();
        ca.MostrarAuxilio(tbauxvial);
        setIconImage(new ImageIcon(getClass().getResource("/Img/mk.jpg")).getImage());
     
    fecha_reg.setEnabled(false);
    id_tecnico.setEnabled(false);
    id_unidad.setEnabled(false);
    incidente.setEnabled(false);
    estatus.setEnabled(false);
    grua.setEnabled(false);
    calle.setEnabled(false);
    colonia.setEnabled(false);
    municipio.setEnabled(false);
    estado.setEnabled(false);
       
    
       Modificar.setEnabled(false);
       Eliminar.setEnabled(false); 
       Guardar.setEnabled(false);
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aux_vial = new javax.swing.JPanel();
        info_gen = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_tecnico = new javax.swing.JTextField();
        id_unidad = new javax.swing.JTextField();
        incidente = new javax.swing.JComboBox<>();
        folio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fecha_reg = new javax.swing.JFormattedTextField();
        lugar_inc = new javax.swing.JPanel();
        txt_calle = new javax.swing.JLabel();
        txt_colonia = new javax.swing.JLabel();
        txt_mun = new javax.swing.JLabel();
        txt_estado = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        municipio = new javax.swing.JComboBox<>();
        colonia = new javax.swing.JTextField();
        calle = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        servicio_ad = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        grua = new javax.swing.JComboBox<>();
        xdddddddd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbauxvial = new javax.swing.JTable();
        servicio_ad1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        estatus = new javax.swing.JComboBox<>();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auxilio Vial");

        aux_vial.setBackground(new java.awt.Color(255, 255, 255));

        info_gen.setBackground(new java.awt.Color(255, 255, 255));
        info_gen.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion general"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ID de Tecnico:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Id Unidad:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tipo de Incidente:");

        id_tecnico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 15), 1, true));
        id_tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_tecnicoActionPerformed(evt);
            }
        });

        id_unidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 15), 1, true));

        incidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daño operativo ", "Diseño débil ", "Mal mantenimiento al sistema", "Fin de vida útil", "Factor Externo " }));

        folio.setEditable(false);
        folio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 15), 1, true));
        folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Numero  Folio:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha de registro:");

        try {
            fecha_reg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fecha_reg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_regActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout info_genLayout = new javax.swing.GroupLayout(info_gen);
        info_gen.setLayout(info_genLayout);
        info_genLayout.setHorizontalGroup(
            info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_genLayout.createSequentialGroup()
                .addGroup(info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_genLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(info_genLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fecha_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addGroup(info_genLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(info_genLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incidente, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info_genLayout.setVerticalGroup(
            info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(id_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(info_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(incidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lugar_inc.setBackground(new java.awt.Color(255, 255, 255));
        lugar_inc.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar de incidencia"));

        txt_calle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_calle.setText("Calle:");

        txt_colonia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_colonia.setText("Colonia:");

        txt_mun.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mun.setText("Municipio:");

        txt_estado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_estado.setText("Estado:");

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo León" }));
        estado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estado.setEnabled(false);

        municipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abasolo", "Agualeguas", "Los Aldamas", "Allende", "Anáhuac", "Apodaca", "Aramberri", "Bustamante", "Cadereyta Jiménez", "El Carmen", "Cerralvo", "Ciénega de Flores", "China", "Dr. Arroyo", "Dr. Coss", "Dr. González", "Galeana", "García", "San Pedro Garza García", "General Bravo", "General Escobedo", "General Terán", "General Treviño", "General Zaragoza", "General Zuazua", "Guadalupe", "Los Herreras", "Higueras", "Hualahuises", "Iturbide", "Juárez", "Lampazos de Naranjo", "Linares", "Marín", "Melchor Ocampo", "Mier y Noriega", "Mina", "Montemorelos", "Monterrey", "Parás", "Pesquería", "Los Ramones", "Rayones", "Sabinas Hidalgo", "Salinas Victoria", "San Nicolás de los Garza", "Hidalgo", "Santa Catarina", "Santiago", "Vallecillo", "Villaldama" }));

        colonia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 15), 1, true));

        calle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 99, 15), 1, true));

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save (1).png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-info.png"))); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete (1).png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lugar_incLayout = new javax.swing.GroupLayout(lugar_inc);
        lugar_inc.setLayout(lugar_incLayout);
        lugar_incLayout.setHorizontalGroup(
            lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lugar_incLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(lugar_incLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lugar_incLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_estado)
                        .addGap(10, 10, 10)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lugar_incLayout.createSequentialGroup()
                        .addGroup(lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lugar_incLayout.createSequentialGroup()
                                .addComponent(txt_calle)
                                .addGap(18, 18, 18)
                                .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                            .addGroup(lugar_incLayout.createSequentialGroup()
                                .addComponent(txt_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colonia)
                                .addGap(17, 17, 17)))
                        .addComponent(txt_mun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        lugar_incLayout.setVerticalGroup(
            lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lugar_incLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mun, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lugar_incLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Modificar)
                    .addComponent(Eliminar)
                    .addComponent(btnnuevo))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        servicio_ad.setBackground(new java.awt.Color(255, 255, 255));
        servicio_ad.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicio adicional"));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Servicio de Grua");

        grua.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        grua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));
        grua.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout servicio_adLayout = new javax.swing.GroupLayout(servicio_ad);
        servicio_ad.setLayout(servicio_adLayout);
        servicio_adLayout.setHorizontalGroup(
            servicio_adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicio_adLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grua, 0, 1, Short.MAX_VALUE)
                .addContainerGap())
        );
        servicio_adLayout.setVerticalGroup(
            servicio_adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicio_adLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(servicio_adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(grua, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        xdddddddd.setBackground(new java.awt.Color(255, 255, 255));
        xdddddddd.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Auxilios viales"));

        tbauxvial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Fecha", "Tecnico", "Unidad", "Incidente", "Estatus", "Grua", "Calle", "Colonia", "Municipio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbauxvial.setColumnSelectionAllowed(true);
        tbauxvial.getTableHeader().setReorderingAllowed(false);
        tbauxvial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbauxvialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbauxvial);
        tbauxvial.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout xddddddddLayout = new javax.swing.GroupLayout(xdddddddd);
        xdddddddd.setLayout(xddddddddLayout);
        xddddddddLayout.setHorizontalGroup(
            xddddddddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xddddddddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        xddddddddLayout.setVerticalGroup(
            xddddddddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xddddddddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        servicio_ad1.setBackground(new java.awt.Color(255, 255, 255));
        servicio_ad1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estatus");

        estatus.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Completado" }));
        estatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout servicio_ad1Layout = new javax.swing.GroupLayout(servicio_ad1);
        servicio_ad1.setLayout(servicio_ad1Layout);
        servicio_ad1Layout.setHorizontalGroup(
            servicio_ad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicio_ad1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicio_ad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicio_ad1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addComponent(estatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        servicio_ad1Layout.setVerticalGroup(
            servicio_ad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicio_ad1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout aux_vialLayout = new javax.swing.GroupLayout(aux_vial);
        aux_vial.setLayout(aux_vialLayout);
        aux_vialLayout.setHorizontalGroup(
            aux_vialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aux_vialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aux_vialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aux_vialLayout.createSequentialGroup()
                        .addComponent(info_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(aux_vialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(servicio_ad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(servicio_ad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(xdddddddd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lugar_inc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aux_vialLayout.setVerticalGroup(
            aux_vialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aux_vialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aux_vialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(aux_vialLayout.createSequentialGroup()
                        .addComponent(servicio_ad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servicio_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(info_gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lugar_inc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xdddddddd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo_mknicarP.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Auxilio vial");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Bregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/previous.png"))); // NOI18N
        Bregresar.setText("Regresar");
        Bregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aux_vial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aux_vial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_tecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_tecnicoActionPerformed

    private void folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folioActionPerformed

    private void tbauxvialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbauxvialMouseClicked
    c_auxilio_vial ca = new c_auxilio_vial();
    fecha_reg.setEnabled(true);
    id_tecnico.setEnabled(true);
    id_unidad.setEnabled(true);
    incidente.setEnabled(true);
    estatus.setEnabled(true);
    grua.setEnabled(true);
    calle.setEnabled(true);
    colonia.setEnabled(true);
    municipio.setEnabled(true);
    estado.setEnabled(true);
    
    Guardar.setEnabled(false);
    Modificar.setEnabled(true);
    Eliminar.setEnabled(true);
    
     
     ca.SeleccionarAuxilio(tbauxvial,folio,fecha_reg, id_tecnico,id_unidad,incidente,estatus,grua,calle,colonia,municipio,estado);
    }//GEN-LAST:event_tbauxvialMouseClicked

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
       c_auxilio_vial ca = new c_auxilio_vial();
        
String fechareg = fecha_reg.getText();
String idtecnico = id_tecnico.getText();
String idunidad = id_unidad.getText();
String call = calle.getText();
String colona = colonia.getText();

        
       if(!"".equals(fechareg)&&!"".equals(idtecnico)&&!"".equals(idunidad)&&!"".equals(call)&&!"".equals(colona)){
           
           
           ca.InsertarAuxilio(fecha_reg, id_tecnico,id_unidad,incidente,estatus,grua,calle,colonia,municipio,estado);
           ca.MostrarAuxilio(tbauxvial);
           //
    folio.setText("");
fecha_reg.setText("");
id_tecnico.setText("");
id_unidad.setText("");
incidente.setSelectedItem("Daño Operativo");
estatus.setSelectedItem("Pendiente");
grua.setSelectedItem("No");
calle.setText("");
colonia.setText("");
municipio.setSelectedItem("Abasolo");
estado.setSelectedItem("Nuevo León");
//
fecha_reg.setEnabled(false);
    id_tecnico.setEnabled(false);
    id_unidad.setEnabled(false);
    incidente.setEnabled(false);
    estatus.setEnabled(false);
    grua.setEnabled(false);
    calle.setEnabled(false);
    colonia.setEnabled(false);
    municipio.setEnabled(false);
    estado.setEnabled(false);
       }
else{
        
           JOptionPane.showMessageDialog(null,"Datos Incompletos, revisar sus datos","Datos incompletos",ERROR_MESSAGE);
       fecha_reg.setEnabled(true);
    id_tecnico.setEnabled(true);
    id_unidad.setEnabled(true);
    incidente.setEnabled(true);
    estatus.setEnabled(true);
    grua.setEnabled(true);
    calle.setEnabled(true);
    colonia.setEnabled(true);
    municipio.setEnabled(true);
    estado.setEnabled(true);
       }        
        
        
        
        
        

        

        
        
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        c_auxilio_vial ca = new c_auxilio_vial();
        
        
int seleccion = JOptionPane.showConfirmDialog(this,"¿Desea editar este registro?","Pregunta",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (seleccion==JOptionPane.YES_OPTION)
        {ca.ModificarAuxilio(folio,fecha_reg, id_tecnico,id_unidad,incidente,estatus,grua,calle,colonia,municipio,estado);
        ca.MostrarAuxilio(tbauxvial);
        
        folio.setText("");
fecha_reg.setText("");
id_tecnico.setText("");
id_unidad.setText("");
incidente.setSelectedItem("Daño Operativo");
estatus.setSelectedItem("Pendiente");
grua.setSelectedItem("No");
calle.setText("");
colonia.setText("");
municipio.setSelectedItem("Abasolo");
estado.setSelectedItem("Nuevo León");

fecha_reg.setEnabled(false);
    id_tecnico.setEnabled(false);
    id_unidad.setEnabled(false);
    incidente.setEnabled(false);
    estatus.setEnabled(false);
    grua.setEnabled(false);
    calle.setEnabled(false);
    colonia.setEnabled(false);
    municipio.setEnabled(false);
    estado.setEnabled(false);
        }
    else if (seleccion==JOptionPane.NO_OPTION){ ca.MostrarAuxilio(tbauxvial);}
        
        
        
        

    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
      c_auxilio_vial ca = new c_auxilio_vial();
      int seleccion = JOptionPane.showConfirmDialog(this,"¿Desea eliminar este registro?","Pregunta",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (seleccion==JOptionPane.YES_OPTION)
        {ca.EliminarAuxilio(folio);
    ca.MostrarAuxilio(tbauxvial);
    
folio.setText("");
fecha_reg.setText("");
id_tecnico.setText("");
id_unidad.setText("");
incidente.setSelectedItem("Daño Operativo");
estatus.setSelectedItem("Pendiente");
grua.setSelectedItem("No");
calle.setText("");
colonia.setText("");
municipio.setSelectedItem("Abasolo");
estado.setSelectedItem("Nuevo León");

    fecha_reg.setEnabled(false);
    id_tecnico.setEnabled(false);
    id_unidad.setEnabled(false);
    incidente.setEnabled(false);
    estatus.setEnabled(false);
    grua.setEnabled(false);
    calle.setEnabled(false);
    colonia.setEnabled(false);
    municipio.setEnabled(false);
    estado.setEnabled(false);
    
    
    
        }
    else if (seleccion==JOptionPane.NO_OPTION){ ca.MostrarAuxilio(tbauxvial);
    fecha_reg.setEnabled(true);
    id_tecnico.setEnabled(true);
    id_unidad.setEnabled(true);
    incidente.setEnabled(true);
    estatus.setEnabled(true);
    grua.setEnabled(true);
    calle.setEnabled(true);
    colonia.setEnabled(true);
    municipio.setEnabled(true);
    estado.setEnabled(true);}
    }//GEN-LAST:event_EliminarActionPerformed

    private void fecha_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_regActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
//set ""
folio.setText("");
fecha_reg.setText("");
id_tecnico.setText("");
id_unidad.setText("");
incidente.setSelectedItem("Daño Operativo");
estatus.setSelectedItem("Pendiente");
grua.setSelectedItem("No");
calle.setText("");
colonia.setText("");
municipio.setSelectedItem("Abasolo");
estado.setSelectedItem("Nuevo León");
//habilitar entradas
fecha_reg.setEnabled(true);
id_tecnico.setEnabled(true);
id_unidad.setEnabled(true);
incidente.setEnabled(true);
estatus.setEnabled(true);
grua.setEnabled(true);
calle.setEnabled(true);
colonia.setEnabled(true);
municipio.setEnabled(true);
estado.setEnabled(true);
//boton deshabilitado
Modificar.setEnabled(false);
Eliminar.setEnabled(false);
//boton habilitado
Guardar.setEnabled(true);

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void BregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregresarActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu mn = new Menu();
        mn.setVisible(true);
    }//GEN-LAST:event_BregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuxilioVial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuxilioVial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuxilioVial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuxilioVial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuxilioVial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bregresar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JPanel aux_vial;
    private javax.swing.JButton btnnuevo;
    public javax.swing.JTextField calle;
    public javax.swing.JTextField colonia;
    public javax.swing.JComboBox<String> estado;
    public javax.swing.JComboBox<String> estatus;
    public javax.swing.JFormattedTextField fecha_reg;
    public javax.swing.JTextField folio;
    public javax.swing.JComboBox<String> grua;
    private javax.swing.JPanel header;
    public javax.swing.JTextField id_tecnico;
    public javax.swing.JTextField id_unidad;
    public javax.swing.JComboBox<String> incidente;
    private javax.swing.JPanel info_gen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lugar_inc;
    public javax.swing.JComboBox<String> municipio;
    private javax.swing.JPanel servicio_ad;
    private javax.swing.JPanel servicio_ad1;
    private javax.swing.JTable tbauxvial;
    private javax.swing.JLabel txt_calle;
    private javax.swing.JLabel txt_colonia;
    private javax.swing.JLabel txt_estado;
    private javax.swing.JLabel txt_mun;
    private javax.swing.JPanel xdddddddd;
    // End of variables declaration//GEN-END:variables
}
