/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;
import Clases.c_inventario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author 1000a
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        
        
        setLocationRelativeTo(null); //para que el formulario se quede en el centro
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Img/mk.jpg")).getImage());
        
        
        c_inventario ci = new c_inventario();
        ci.MostrarInventario(jTable1);
        
      
        Eliminar.setEnabled(false);
        Nuevo.setEnabled(true);
        Modificar.setEnabled(false);
        Guardar.setEnabled(false);
        
        
        
    }
    private TableRowSorter trsfiltro;
    public void filtro() {
    trsfiltro.setRowFilter(RowFilter.regexFilter("(?i)"+txtbuscar.getText(), 2));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Icono = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Tabpaneles = new javax.swing.JTabbedPane();
        Inventario = new javax.swing.JPanel();
        buscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Eliminar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        Bregresar = new javax.swing.JButton();
        Entradas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_sku = new javax.swing.JFormattedTextField();
        txt_modelo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        txt_existencias = new javax.swing.JFormattedTextField();
        Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");

        Header.setBackground(new java.awt.Color(102, 102, 102));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo_mknicarP.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Inventario");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Icono)
                .addGap(23, 23, 23))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Tabpaneles.setBackground(new java.awt.Color(255, 255, 255));

        Inventario.setBackground(new java.awt.Color(255, 255, 255));

        buscar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        buscar.setText("Buscar por modelo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SKU", "Descripcion", "Modelo de pieza", "Existencias"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete (1).png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        Bregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/previous.png"))); // NOI18N
        Bregresar.setText("Regresar");
        Bregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InventarioLayout = new javax.swing.GroupLayout(Inventario);
        Inventario.setLayout(InventarioLayout);
        InventarioLayout.setHorizontalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Eliminar)
                .addGap(119, 119, 119))
            .addGroup(InventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventarioLayout.createSequentialGroup()
                        .addComponent(buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InventarioLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(Bregresar)
                    .addContainerGap(411, Short.MAX_VALUE)))
        );
        InventarioLayout.setVerticalGroup(
            InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Eliminar)
                .addContainerGap())
            .addGroup(InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InventarioLayout.createSequentialGroup()
                    .addGap(320, 320, 320)
                    .addComponent(Bregresar)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        Tabpaneles.addTab("Inventario", Inventario);

        Entradas.setBackground(new java.awt.Color(255, 255, 255));
        Entradas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 104, 140)), "Datos del producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("SKU");

        txt_sku.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 106, 140), 1, true));
        txt_sku.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_sku.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_modelo.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_modelo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 106, 140), 1, true));
        txt_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modeloActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Modelo pieza");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Descripcion");

        txt_descripcion.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        txt_descripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 106, 140), 1, true));
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });

        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save (1).png"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Existencias");

        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit-info.png"))); // NOI18N
        Modificar.setText("Crear cambio");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        txt_existencias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 106, 140), 1, true));
        txt_existencias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_existencias.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save (1).png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EntradasLayout = new javax.swing.GroupLayout(Entradas);
        Entradas.setLayout(EntradasLayout);
        EntradasLayout.setHorizontalGroup(
            EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntradasLayout.createSequentialGroup()
                .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntradasLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modificar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntradasLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EntradasLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_sku, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addGap(10, 10, 10)
                                .addComponent(txt_existencias, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EntradasLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(10, 10, 10)
                                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EntradasLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        EntradasLayout.setVerticalGroup(
            EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntradasLayout.createSequentialGroup()
                .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntradasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sku, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntradasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_existencias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntradasLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EntradasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        Tabpaneles.addTab("Entradas", Entradas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabpaneles)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabpaneles))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
    
    
    String existencias =  txt_existencias.getText();
    String modelo = txt_modelo.getText();
    String descripcion = txt_descripcion.getText();
    
    if(!"".equals(existencias)&&!"".equals(modelo)&&!"".equals(descripcion))
    {
    
    c_inventario ci = new c_inventario();
    ci.ModificarInventario(txt_existencias, txt_modelo, txt_descripcion,txt_sku);
    ci.MostrarInventario(jTable1);
    txt_existencias.setEnabled(false);
    txt_modelo.setEnabled(false);
    txt_descripcion.setEnabled(false);
    
    txt_sku.setText("");
    txt_existencias.setText("");
    txt_modelo.setText("");
    txt_descripcion.setText("");
    
    
    }
    else{ JOptionPane.showMessageDialog(null,"Datos Incompletos, revisar sus datos","Datos incompletos",ERROR_MESSAGE);}
    
    }//GEN-LAST:event_ModificarActionPerformed

    private void txt_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modeloActionPerformed

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
    
    
    Guardar.setEnabled(true);
    Modificar.setEnabled(false);
    
    txt_descripcion.setEnabled(true);
    txt_existencias.setEnabled(true);
    txt_modelo.setEnabled(true);
   
    txt_sku.setText("");
    txt_existencias.setText("");
    txt_modelo.setText("");
    txt_descripcion.setText("");

    }//GEN-LAST:event_NuevoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
         c_inventario ci = new c_inventario();
    int seleccion = JOptionPane.showConfirmDialog(this,"¿Desea eliminar este registro?","Pregunta",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
    if (seleccion==JOptionPane.YES_OPTION){
    
   
    ci.EliminarInventario(txt_sku);
    ci.MostrarInventario(jTable1);}
        else if(seleccion==JOptionPane.NO_OPTION){
                    }
    }//GEN-LAST:event_EliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        Guardar.setEnabled(false);
        txt_existencias.setEnabled(true);
        txt_descripcion.setEnabled(true);
      txt_modelo.setEnabled(true);
        Eliminar.setEnabled(true);
        txt_sku.setEnabled(false);
        Modificar.setEnabled(true);
    c_inventario ci = new c_inventario();
    ci.SeleccionarInventario(jTable1, txt_sku, txt_existencias, txt_modelo, txt_descripcion);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
    txtbuscar.addKeyListener(new KeyAdapter() {
    @Override
    public void keyReleased(KeyEvent e) {
trsfiltro.setRowFilter(RowFilter.regexFilter("(?i)"+txtbuscar.getText(), 2));
}
});
trsfiltro = new TableRowSorter(jTable1.getModel());
jTable1.setRowSorter(trsfiltro);
        
        
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void BregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu mn = new Menu();
        mn.setVisible(true);
    }//GEN-LAST:event_BregresarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
    
    String existencias =  txt_existencias.getText();
    String modelo = txt_modelo.getText();
    String descripcion = txt_descripcion.getText();
    
    if(!"".equals(existencias)&&!"".equals(modelo)&&!"".equals(descripcion))
    {
    
    c_inventario ci = new c_inventario();
    ci.InsertarInventario(txt_existencias, txt_modelo,txt_descripcion);        
    ci.MostrarInventario(jTable1);
    txt_existencias.setEnabled(false);
    txt_modelo.setEnabled(false);
    txt_descripcion.setEnabled(false);
    
    txt_sku.setText("");
    txt_existencias.setText("");
    txt_modelo.setText("");
    txt_descripcion.setText("");
    
    
    }
    else{ JOptionPane.showMessageDialog(null,"Datos Incompletos, revisar sus datos","Datos incompletos",ERROR_MESSAGE);}
            // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bregresar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JPanel Entradas;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Icono;
    private javax.swing.JPanel Inventario;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTabbedPane Tabpaneles;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JFormattedTextField txt_existencias;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JFormattedTextField txt_sku;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
